### ISSUE TITLE
水仙花数的栗子部分内容有误

### ISSUE THREAD

**Issue by tabooc** [OBKoro1/web_accumulate#4]
http://obkoro1.com/web_accumulate/algorithm/induction/%E6%B0%B4%E4%BB%99%E8%8A%B1%E6%95%B0.html

根据定义
<div><i>n</i>&nbsp;=&nbsp;<i>d</i><sub><i>k</i></sub><sup><i>k</i></sup>&nbsp;+&nbsp;<i>d</i><sub><i>k</i>-1</sub><sup><i>k</i></sup>&nbsp;+&nbsp;...&nbsp;+&nbsp;<i>d</i><sub>2</sub><sup><i>k</i></sup>&nbsp;+&nbsp;<i>d</i><sub>1</sub><sup><i>k</i></sup>.</div>
，栗子部分内容有误，例如第一条应当是：

<div>153&nbsp;=&nbsp;1<sup>3</sup>&nbsp;+&nbsp;5<sup>3</sup>&nbsp;+&nbsp;3<sup>3</sup>。</div>

**Comment by OBKoro1** [comment]
@tabooc 感谢指正，下次发布博客的时候会更正。
